# Generated by Django 5.0.1 on 2025-09-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_product_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_identifier',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
