# Generated by Django 5.0.1 on 2025-09-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_order_order_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sales_identifier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
