# Generated by Django 5.0.1 on 2025-09-03 07:44

from django.db import migrations
from django.utils import timezone


def populate_sales_identifiers(apps, schema_editor):
    Sales = apps.get_model('business', 'Sales')
    
    # Get all sales without identifiers
    sales_without_id = Sales.objects.filter(sales_identifier='')
    
    for sale in sales_without_id:
        # Generate identifier for existing sales
        current_year = timezone.now().year
        
        # Get the last sales record for this year
        last_sales = Sales.objects.filter(
            sales_identifier__startswith=f'TSRT-{current_year}'
        ).exclude(sales_identifier='').order_by('-sales_identifier').first()
        
        if last_sales and last_sales.sales_identifier:
            try:
                parts = last_sales.sales_identifier.split('-')
                if len(parts) == 3 and parts[1] == str(current_year):
                    last_number = int(parts[2])
                    next_number = last_number + 1
                else:
                    next_number = 1
            except (IndexError, ValueError):
                next_number = 1
        else:
            next_number = 1
        
        # Format with leading zeros
        sale.sales_identifier = f"TSRT-{current_year}-{next_number:02d}"
        sale.save()


def reverse_populate_sales_identifiers(apps, schema_editor):
    Sales = apps.get_model('business', 'Sales')
    Sales.objects.all().update(sales_identifier='')


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_sales_sales_identifier'),
    ]

    operations = [
        migrations.RunPython(populate_sales_identifiers, reverse_populate_sales_identifiers),
    ]
