# Generated by Django 5.0.1 on 2025-09-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20250903_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sales_identifier',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
