# Generated by Django 5.2.6 on 2025-09-15 10:44

from django.db import migrations


def create_categories(apps, schema_editor):
    Category = apps.get_model('business', 'Category')
    
    # Create the specific categories for rental items
    categories = [
        {'name': 'Barong', 'description': 'Traditional Filipino formal wear'},
        {'name': 'Suits', 'description': 'Formal business suits'},
        {'name': 'Coat', 'description': 'Formal coats and jackets'},
        {'name': 'Pants', 'description': 'Formal pants and trousers'},
    ]
    
    for category_data in categories:
        Category.objects.get_or_create(
            name=category_data['name'],
            defaults={'description': category_data['description']}
        )


def reverse_create_categories(apps, schema_editor):
    Category = apps.get_model('business', 'Category')
    Category.objects.filter(name__in=['Barong', 'Suits', 'Coat', 'Pants']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_activitylog'),
    ]

    operations = [
        migrations.RunPython(create_categories, reverse_create_categories),
    ]
