# Generated by Django 5.2.6 on 2025-09-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20250915_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('rental', 'Rental Item'), ('material', 'Material')], max_length=20),
        ),
    ]
