# Generated by Django 5.2.6 on 2025-09-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('rented', 'Rented'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
