# Generated by Django 5.2.6 on 2025-09-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('repair', 'Repair'), ('customize', 'Customize')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('rented', 'Rented'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
