# Generated by Django 5.0.1 on 2025-09-27 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_add_overdue_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_type', models.CharField(choices=[('per_piece', 'Per Piece'), ('per_bundle', 'Per Bundle'), ('per_meter', 'Per Meter'), ('per_yard', 'Per Yard'), ('per_kg', 'Per Kilogram'), ('per_dozen', 'Per Dozen')], max_length=20)),
                ('bundle_size', models.PositiveIntegerField(blank=True, help_text='Number of pieces in a bundle (if applicable)', null=True)),
                ('buy_price_per_unit', models.DecimalField(decimal_places=2, help_text='Price you buy this material for', max_digits=10)),
                ('sell_price_per_unit', models.DecimalField(decimal_places=2, help_text='Price you sell this material for', max_digits=10)),
                ('is_default', models.BooleanField(default=False, help_text='Default pricing option for this material type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Material Pricing Options',
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('unit_of_measurement', models.CharField(help_text='e.g., piece, meter, yard, bundle', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Material Types',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='current_quantity_in_stock',
            field=models.PositiveIntegerField(default=0, help_text='Current quantity in stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measurement',
            field=models.CharField(blank=True, help_text='Unit of measurement for this material', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_pricing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='business.materialpricing'),
        ),
        migrations.AddField(
            model_name='materialpricing',
            name='material_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='business.materialtype'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.materialtype'),
        ),
        migrations.AlterUniqueTogether(
            name='materialpricing',
            unique_together={('material_type', 'pricing_type', 'bundle_size')},
        ),
    ]
