# Generated by Django 5.2.6 on 2025-09-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_materialpricing_materialtype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialpricing',
            options={'ordering': ['material_type', 'pricing_type'], 'verbose_name_plural': 'Material Pricing Options'},
        ),
        migrations.AlterModelOptions(
            name='materialtype',
            options={'ordering': ['name'], 'verbose_name_plural': 'Material Types'},
        ),
    ]
