# Generated by Django 5.0.1 on 2025-10-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_alter_materialpricing_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_by',
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Deposit amount (1000)', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='product_base_price',
            field=models.DecimalField(decimal_places=2, default=500, help_text='Product base price (500)', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='rental_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rental fee (1500)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('rented', 'Rented'), ('almost_due', 'Almost Due'), ('due', 'Due'), ('overdue', 'Overdue'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
