# Generated by Django 5.0.1 on 2025-10-01 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_rental_pricing_and_status_updates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='created_by',
        ),
    ]
