# Generated by Django 5.0.1 on 2025-11-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, help_text='Background image for the system', null=True, upload_to='system/backgrounds/')),
                ('is_active', models.BooleanField(default=True, help_text='Only one active setting is used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
