# Generated by Django 5.2.6 on 2025-11-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('rental', 'Rental Item'), ('material', 'Material'), ('service', 'Service')], max_length=20),
        ),
    ]
