# Generated by Django 5.2.6 on 2025-11-14 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_order_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetcode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='order',
            name='customize_image',
            field=models.ImageField(blank=True, help_text='Uploaded customize product image (if not from existing products)', null=True, upload_to='customize_orders/'),
        ),
        migrations.AddField(
            model_name='order',
            name='customize_product_reference',
            field=models.ForeignKey(blank=True, help_text='Reference to customize product (uniform/PE) selected or uploaded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customize_orders', to='business.product'),
        ),
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
