# Generated by Django 5.2.6 on 2025-11-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_remove_passwordresetcode_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archive completed orders to keep them in reports but hide from orders list'),
        ),
    ]
