# Generated by Django 5.2.6 on 2025-11-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('rented', 'Rented'), ('returned', 'Returned'), ('almost_due', 'Almost Due'), ('due', 'Due'), ('overdue', 'Overdue'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
