# Generated by Django 5.0.1 on 2025-11-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('rented', 'Rented'), ('returned', 'Returned'), ('almost_due', 'Almost Due'), ('due', 'Due'), ('overdue', 'Overdue'), ('ready_to_pick_up', 'Ready to Pick Up'), ('repair_done', 'Repair Done'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
