# Generated by Django 5.2.7 on 2025-11-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='cash', help_text='Payment method used for this order', max_length=50),
        ),
    ]
