# Generated by Django 5.0.1 on 2025-12-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0030_order_assigned_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='staff_assigned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when staff was assigned to this order', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='staff_completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when staff marked the order as done', null=True),
        ),
    ]
