# Generated by Django 5.2.7 on 2025-12-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0032_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Staff phone number', max_length=20, null=True),
        ),
    ]
