# Generated by Django 5.2.7 on 2025-12-07 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0034_add_password_reset_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_amount', models.DecimalField(decimal_places=2, help_text='Amount withdrawn (staff share)', max_digits=10)),
                ('total_revenue', models.DecimalField(decimal_places=2, help_text='Total revenue at time of withdrawal', max_digits=10)),
                ('owner_share', models.DecimalField(decimal_places=2, help_text='Owner share at time of withdrawal', max_digits=10)),
                ('completed_orders_count', models.PositiveIntegerField(default=0, help_text='Number of completed orders at withdrawal')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the withdrawal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
                ('withdrawn_by', models.ForeignKey(help_text='User who processed the withdrawal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Withdrawal',
                'verbose_name_plural': 'Staff Withdrawals',
                'ordering': ['-created_at'],
            },
        ),
    ]
