# Generated by Django 5.2.7 on 2025-12-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0035_staffwithdrawal_delete_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('hero', 'Hero Section Image'), ('service_repair', 'Service - Repair'), ('service_customize', 'Service - Customize'), ('service_uniform', 'Service - Uniform Making'), ('service_patches', 'Service - Patches'), ('service_rental', 'Service - Rental'), ('about_workshop', 'About - Workshop'), ('about_tailor', 'About - Tailor'), ('fabric_cotton', 'Fabric - Cotton'), ('fabric_linen', 'Fabric - Linen'), ('fabric_wool', 'Fabric - Wool'), ('fabric_leather', 'Fabric - Leather'), ('fabric_silk', 'Fabric - Silk'), ('shop_exterior', 'Shop - Exterior'), ('shop_interior', 'Shop - Interior')], help_text='Type of image for the landing page', max_length=50, unique=True)),
                ('image', models.ImageField(help_text='Image file for the landing page', upload_to='landing_page/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for the image', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this image is currently displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Image',
                'verbose_name_plural': 'Landing Page Images',
                'ordering': ['image_type'],
            },
        ),
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
    ]
