# Generated by Django 5.2.7 on 2025-12-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0036_landingpageimage_delete_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpageimage',
            name='image_type',
            field=models.CharField(choices=[('hero', 'Hero Section Image'), ('service_repair', 'Service - Repair'), ('service_customize', 'Service - Customize'), ('service_uniform', 'Service - Uniform Making'), ('service_patches', 'Service - Patches'), ('service_rental', 'Service - Rental'), ('about_workshop', 'About - Workshop'), ('about_tailor', 'About - Tailor'), ('fabric_cotton', 'Fabric - Cotton'), ('fabric_linen', 'Fabric - Linen'), ('fabric_wool', 'Fabric - Wool'), ('fabric_leather', 'Fabric - Leather'), ('fabric_silk', 'Fabric - Silk'), ('shop_exterior', 'Shop - Exterior'), ('shop_exterior_2', 'Shop - Exterior 2'), ('shop_interior', 'Shop - Interior'), ('shop_interior_2', 'Shop - Interior 2')], help_text='Type of image for the landing page', max_length=50, unique=True),
        ),
    ]
